export const INITIAL_FLIGHTS = [
  {
    id: "fl_1",
    flight: "N41402",
    flight_date: "25.08",
    route_city: "Москва",
    route_airports: "KQT-SVO",
    time: "14:20",
    release_time: "13:40",
    ac_num: "73314",
    ac_config: "189",
    pax: "146",
    crew: "2/4/0/0",
    fuel_block: "12500",
    fuel_trip: "9800",
    fuel_taxi: "300",
    dow: "42150",
    doi: "48.2",
    galley: "D",
    lir_sent: true,
    mtow: "79000",
    cargo: "450кг",
    mail: "120кг",
    baggage: "1850кг (VIP 2)",
    szv_sent: true,
    ldm_sent: true,
    status: "closed",
    notes: "VIP на борту 2C"
  },
  {
    id: "fl_2",
    flight: "EO413",
    flight_date: "25.08",
    route_city: "Казань",
    route_airports: "AER-KZN",
    time: "13:41",
    release_time: "13:01",
    ac_num: "73344",
    ac_config: "215",
    pax: "203",
    crew: "2/5/1/0",
    fuel_block: "14200",
    fuel_trip: "11500",
    fuel_taxi: "350",
    dow: "43200",
    doi: "49.1",
    galley: "D",
    lir_sent: true,
    mtow: "78200",
    cargo: "820кг",
    mail: "",
    baggage: "Хрупкий спецбагаж",
    szv_sent: true,
    ldm_sent: false,
    status: "released",
    notes: "Спецбагаж (хрупкий)"
  },
  {
    id: "fl_3",
    flight: "N4411",
    flight_date: "25.08",
    route_city: "Казань",
    route_airports: "AER-KZN",
    time: "14:42",
    release_time: "14:02",
    ac_num: "73270",
    ac_config: "220",
    pax: "210",
    crew: "3/6/0/0",
    fuel_block: "15100",
    fuel_trip: "12200",
    fuel_taxi: "400",
    dow: "44100",
    doi: "47.8",
    galley: "D",
    lir_sent: true,
    mtow: "79000",
    cargo: "310кг",
    mail: "",
    baggage: "Трансфер 14 мест",
    szv_sent: false,
    ldm_sent: false,
    status: "lir_sent",
    notes: "LIR успешно отправлен"
  },
  {
    id: "fl_4",
    flight: "N4079",
    flight_date: "25.08",
    route_city: "Оренбург",
    route_airports: "REN-SVO",
    time: "15:20",
    release_time: "14:40",
    ac_num: "73325",
    ac_config: "189",
    pax: "172",
    crew: "2/4/0/0",
    fuel_block: "11800",
    fuel_trip: "8900",
    fuel_taxi: "300",
    dow: "41900",
    doi: "48.5",
    galley: "D",
    lir_sent: true,
    mtow: "79000",
    cargo: "150кг",
    mail: "",
    baggage: "Прямой",
    szv_sent: false,
    ldm_sent: false,
    astra_times_sent: false,
    status: "prepared",
    notes: "Рейс из REN: после взлёта проставить времена движения и взлёта в Astra"
  },
  {
    id: "fl_5",
    flight: "N4429",
    flight_date: "25.08",
    route_city: "Нижнекамск",
    route_airports: "AER-NBC",
    time: "17:12",
    release_time: "16:32",
    ac_num: "73305",
    ac_config: "189",
    pax: "189",
    crew: "2/4/0/0",
    fuel_block: "",
    fuel_trip: "",
    fuel_taxi: "",
    dow: "",
    doi: "",
    galley: "D",
    lir_sent: false,
    mtow: "",
    cargo: "",
    mail: "",
    baggage: "",
    szv_sent: false,
    ldm_sent: false,
    status: "pending",
    notes: "100% загрузка"
  },
  {
    id: "fl_6",
    flight: "EO487",
    flight_date: "26.08",
    route_city: "Москва",
    route_airports: "SVO-SVO",
    time: "06:40",
    release_time: "06:00",
    ac_num: "73318",
    ac_config: "189",
    pax: "0",
    crew: "2/3/1/0",
    fuel_block: "8500",
    fuel_trip: "6200",
    fuel_taxi: "250",
    dow: "41900",
    doi: "46.5",
    galley: "D",
    lir_sent: false,
    mtow: "79000",
    cargo: "",
    mail: "",
    baggage: "Без багажа (0 PAX)",
    szv_sent: false,
    ldm_sent: false,
    status: "pending",
    notes: "Технический перегон"
  }
];
